### ISSUE TITLE
history路由模式发版上线要注意哪些问题？

### ISSUE THREAD

**Issue by zhengbangbo** [lvjiaxuan/interview#4]

**Comment by zhengbangbo** [comment]
对于常用的前端应用部署平台可以这样配置

## Vercel
```json
// vercel.json
{
  "rewrites":  [
    {"source": "/(.*)", "destination": "/index.html"}
  ]
}
```

## Netlify
```toml
// netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
